### PR TITLE
feat: Added test for Config and fixed errors in it

### PR DESCRIPTION
**Pull request by rushitote**
Added the test for Config which gave this final output:
```
.
Ran 1 tests in 0.001 seconds, 1 success, 0 failures
OK

```

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner plz review.

**Comment by hsluoyz** [comment]
@rushitote why close?

**Comment by rushitote** [comment]
@hsluoyz This was implemented with `luaunit`, I will do again with `busted` instead.

**Comment by hsluoyz** [comment]
@rushitote good!

**Pull request closed without merging**
