### PR TITLE
feat: Added RBAC API

### PR DESCRIPTION
**Pull request by rushitote**
- RBAC API (without domains) was added
- Added functions for `BatchEnforce`, `AddNamedMatchingFunc`, `AddNamedDomainMatchingFunc`

Next, I will add the remaining RBAC API (with domains) and then RBAC API tests.

### CODE REVIEW

**Comment by rushitote** [comment]
Added the remaining RBAC API (with domains), next I will be working on tests for this.

@techoner @hsluoyz Please review.

**Comment by techoner** [comment]
@rushitote  Why not add unit tests together ?

**Comment by rushitote** [comment]
@techoner Sure, I am working on it.

**Review by techoner — CHANGES_REQUESTED** [review]
Waiting for your unit test .

**Comment by rushitote** [comment]
@techoner Added the unit test.

**Comment by rushitote** [comment]
@techoner Can you please review this?

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
