### PR TITLE
feat: Added tests for Model/Policy module and fixed errors in it

### PR DESCRIPTION
**Pull request by rushitote**
- fix: Error in config file
- Added test for adding/removing/updating single and multiple policies
- Added examples from [casbin/casbin](https://github.com/casbin/casbin)

### CODE REVIEW

**Comment by rushitote** [comment]
There seems to be some error with installing dependencies from luarocks.org.

**Comment by hsluoyz** [comment]
> There seems to be some problem with installing dependencies from luarocks.org.

How to fix it?

**Comment by rushitote** [comment]
@hsluoyz 
I tried to rerun the tests and it's just hit or miss for all of  the test runs so maybe it's a server issue from LuaRocks.

**Comment by rushitote** [comment]
@hsluoyz I edited the workflow to run the install command until it succeeds and now it seems to work.

**Comment by hsluoyz** [comment]
@techoner

**Pull request merged**
