### PR TITLE
feat: Implemented Role Manager module and fix: errors in Assertion

### PR DESCRIPTION
**Pull request by rushitote**
I will try to add unit test for this module in few days.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner

**Comment by hsluoyz** [comment]
@rushitote plz fix:

image

**Comment by rushitote** [comment]
@hsluoyz I added a utility function to check if two tables have same values regardless of order since it seems the Busted function to check if two tables are same compares it in different ways (orders) on different Lua versions. Now the checks run fine.

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
