### PR TITLE
feat: Added utility and config tests with busted library

### PR DESCRIPTION
**Pull request by rushitote**
Ported tests from the previous utility and config test modules which used `luaunit`.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner

**Comment by hsluoyz** [comment]
@rushitote plz fix the checks:

image

**Comment by rushitote** [comment]
@hsluoyz 
Yes, the utility test module works fine but the newer config test module has some issue with path of the `test.ini` file. I tried 2 methods to get the path of that file - while they both run fine on my PC they give error here. I will try to fix this.

**Comment by rushitote** [comment]
@hsluoyz now all checks run successfully.

**Comment by hsluoyz** [comment]
@techoner

**Comment by rushitote** [comment]
@techoner Can you please check the DM from me on Gitter? I wanted some feedback on a draft of my proposal that I have created. Thank you!

**Pull request merged**
